export type CommuneSeed = {
  name: string;
  slug: string;
  departmentSlug: string;
  lat: number;
  lng: number;
  population?: number;
  description?: string;
};

// Jeu de données : référentiel officiel complet pour les régions de Dakar,
// Ziguinchor, Fatick, Kaolack et Thiès ; pour les 9 autres régions, seed
// démonstratif (le chef-lieu de chaque département, complété par quelques
// communes notables). À compléter avec le référentiel officiel ANSD/Code des
// collectivités locales (~557 communes au total) avant une mise en production.
export const communes: CommuneSeed[] = [
  // Dakar (département) — 19 communes
  { name: "Ngor", slug: "ngor", departmentSlug: "dakar-dept", lat: 14.7444, lng: -17.5125 },
  { name: "Biscuiterie", slug: "biscuiterie", departmentSlug: "dakar-dept", lat: 14.718, lng: -17.452 },
  { name: "Mermoz-Sacré-Coeur", slug: "mermoz-sacre-coeur", departmentSlug: "dakar-dept", lat: 14.7167, lng: -17.4667 },
  { name: "Camberène", slug: "camberene", departmentSlug: "dakar-dept", lat: 14.7561, lng: -17.4419 },
  { name: "Colobane-Fass-Gueule Tapée", slug: "colobane-fass-gueule-tapee", departmentSlug: "dakar-dept", lat: 14.6917, lng: -17.4472 },
  { name: "Dieuppeul-Derklé", slug: "dieuppeul-derkle", departmentSlug: "dakar-dept", lat: 14.7167, lng: -17.45 },
  { name: "Fann-Point E-Amitié", slug: "fann-point-e-amitie", departmentSlug: "dakar-dept", lat: 14.6889, lng: -17.4583 },
  { name: "Gorée", slug: "goree", departmentSlug: "dakar-dept", lat: 14.6667, lng: -17.3983, description: "Île historique classée patrimoine mondial de l'UNESCO." },
  { name: "Grand Dakar", slug: "grand-dakar", departmentSlug: "dakar-dept", lat: 14.7222, lng: -17.4472 },
  { name: "Grand Yoff", slug: "grand-yoff", departmentSlug: "dakar-dept", lat: 14.7333, lng: -17.45 },
  { name: "Hann Bel-Air", slug: "hann-bel-air", departmentSlug: "dakar-dept", lat: 14.7083, lng: -17.425 },
  { name: "HLM", slug: "hlm", departmentSlug: "dakar-dept", lat: 14.7083, lng: -17.45 },
  { name: "Médina", slug: "medina", departmentSlug: "dakar-dept", lat: 14.6833, lng: -17.4444 },
  { name: "Ouakam", slug: "ouakam", departmentSlug: "dakar-dept", lat: 14.7167, lng: -17.4833 },
  { name: "Parcelles Assainies", slug: "parcelles-assainies", departmentSlug: "dakar-dept", lat: 14.75, lng: -17.4333 },
  { name: "Patte d'Oie", slug: "patte-doie", departmentSlug: "dakar-dept", lat: 14.7333, lng: -17.4417 },
  { name: "Plateau", slug: "plateau", departmentSlug: "dakar-dept", lat: 14.6708, lng: -17.4314, description: "Centre historique, administratif et économique de Dakar." },
  { name: "Sicap Liberté", slug: "sicap-liberte", departmentSlug: "dakar-dept", lat: 14.7028, lng: -17.4583 },
  { name: "Yoff", slug: "yoff", departmentSlug: "dakar-dept", lat: 14.7458, lng: -17.4856 },
  // Guédiawaye (département) — 5 communes
  { name: "Ndiarème Limamoulaye", slug: "ndiareme-limamoulaye", departmentSlug: "guediawaye", lat: 14.7722, lng: -17.4083 },
  { name: "Golf Sud", slug: "golf-sud", departmentSlug: "guediawaye", lat: 14.7667, lng: -17.3917 },
  { name: "Médina Gounass", slug: "medina-gounass", departmentSlug: "guediawaye", lat: 14.7806, lng: -17.4014 },
  { name: "Sam Notaire", slug: "sam-notaire", departmentSlug: "guediawaye", lat: 14.775, lng: -17.4111 },
  { name: "Wakhinane Nimzatt", slug: "wakhinane-nimzatt", departmentSlug: "guediawaye", lat: 14.7639, lng: -17.3972 },
  // Pikine (département) — 15 communes (Keur Massar est désormais son propre département, voir plus bas)
  { name: "Dalifort", slug: "dalifort", departmentSlug: "pikine", lat: 14.7306, lng: -17.4083 },
  { name: "Diack Sao", slug: "diack-sao", departmentSlug: "pikine", lat: 14.755, lng: -17.3833 },
  { name: "Diamaguène Sicap M'Bao", slug: "diamaguene-sicap-mbao", departmentSlug: "pikine", lat: 14.7444, lng: -17.3722 },
  { name: "Djidah Thiaroye Kao", slug: "djidah-thiaroye-kao", departmentSlug: "pikine", lat: 14.7611, lng: -17.3889 },
  { name: "Guinaw Rails Nord", slug: "guinaw-rails-nord", departmentSlug: "pikine", lat: 14.7472, lng: -17.4028 },
  { name: "Guinaw Rails Sud", slug: "guinaw-rails-sud", departmentSlug: "pikine", lat: 14.7417, lng: -17.4028 },
  { name: "M'Bao", slug: "mbao", departmentSlug: "pikine", lat: 14.7389, lng: -17.3639 },
  { name: "Malika", slug: "malika", departmentSlug: "pikine", lat: 14.7833, lng: -17.35 },
  { name: "Pikine Est", slug: "pikine-est", departmentSlug: "pikine", lat: 14.7556, lng: -17.3917 },
  { name: "Pikine Ouest", slug: "pikine-ouest", departmentSlug: "pikine", lat: 14.7611, lng: -17.4028 },
  { name: "Pikine Sud", slug: "pikine-sud", departmentSlug: "pikine", lat: 14.7472, lng: -17.3972 },
  { name: "Thiaroye-sur-Mer", slug: "thiaroye-sur-mer", departmentSlug: "pikine", lat: 14.7333, lng: -17.3806 },
  { name: "Thiaroye Gare", slug: "thiaroye-gare", departmentSlug: "pikine", lat: 14.7472, lng: -17.375 },
  { name: "Yeumbeul Nord", slug: "yeumbeul-nord", departmentSlug: "pikine", lat: 14.7694, lng: -17.3722 },
  { name: "Yeumbeul Sud", slug: "yeumbeul-sud", departmentSlug: "pikine", lat: 14.7611, lng: -17.3694 },
  // Rufisque (département) — 12 communes
  { name: "Bambilor", slug: "bambilor", departmentSlug: "rufisque", lat: 14.8167, lng: -17.2667 },
  { name: "Bargny", slug: "bargny", departmentSlug: "rufisque", lat: 14.6997, lng: -17.2236 },
  { name: "Diamniadio", slug: "diamniadio", departmentSlug: "rufisque", lat: 14.7167, lng: -17.1833, description: "Pôle urbain en plein essor, siège de nombreux projets d'infrastructures nationales." },
  { name: "Jaxaay-Parcelle-Niakoul Rap", slug: "jaxaay-parcelle-niakoul-rap", departmentSlug: "rufisque", lat: 14.7667, lng: -17.3167 },
  { name: "Sangalkam", slug: "sangalkam", departmentSlug: "rufisque", lat: 14.7667, lng: -17.2167 },
  { name: "Sébikotane", slug: "sebikotane", departmentSlug: "rufisque", lat: 14.75, lng: -17.1333 },
  { name: "Sendou", slug: "sendou", departmentSlug: "rufisque", lat: 14.7167, lng: -17.2333 },
  { name: "Rufisque Est", slug: "rufisque-est", departmentSlug: "rufisque", lat: 14.7167, lng: -17.2583 },
  { name: "Rufisque Centre", slug: "rufisque-centre", departmentSlug: "rufisque", lat: 14.7194, lng: -17.2667 },
  { name: "Rufisque Ouest", slug: "rufisque-ouest", departmentSlug: "rufisque", lat: 14.7222, lng: -17.2722 },
  { name: "Tivaouane Peulh-Niagha", slug: "tivaouane-peulh-niagha", departmentSlug: "rufisque", lat: 14.8167, lng: -17.3333 },
  { name: "Yène", slug: "yene", departmentSlug: "rufisque", lat: 14.6333, lng: -17.15 },
  // Keur Massar (département, créé en 2021 par scission de Pikine)
  { name: "Keur Massar", slug: "keur-massar", departmentSlug: "keur-massar", lat: 14.7833, lng: -17.3167, population: 350000 },
  // Mbour (département) — référentiel officiel, 16 communes
  { name: "Ndiaganiao", slug: "ndiaganiao", departmentSlug: "mbour", lat: 14.5167, lng: -16.85 },
  { name: "Nguéniène", slug: "ngueniene", departmentSlug: "mbour", lat: 14.3, lng: -16.7833 },
  { name: "Ngaparou", slug: "ngaparou", departmentSlug: "mbour", lat: 14.45, lng: -17.0333 },
  { name: "Nguékhokh", slug: "nguekhokh", departmentSlug: "mbour", lat: 14.4833, lng: -17.0167 },
  { name: "Joal-Fadiouth", slug: "joal-fadiouth", departmentSlug: "mbour", lat: 14.1667, lng: -16.8333, population: 38000, description: "Village de pêcheurs connu pour son île-cimetière de Fadiouth bâtie en coquillages." },
  { name: "Mbour", slug: "mbour", departmentSlug: "mbour", lat: 14.4204, lng: -16.9646, population: 150000 },
  { name: "Popoguine", slug: "popoguine", departmentSlug: "mbour", lat: 14.5167, lng: -17.1 },
  { name: "Saly Portudal", slug: "saly-portudal", departmentSlug: "mbour", lat: 14.45, lng: -17.0167, population: 20000, description: "Station touristique balnéaire majeure de la Petite Côte." },
  { name: "Somone", slug: "somone", departmentSlug: "mbour", lat: 14.4667, lng: -17.05 },
  { name: "Thiadiaye", slug: "thiadiaye", departmentSlug: "mbour", lat: 14.2667, lng: -16.7333 },
  { name: "Diass", slug: "diass", departmentSlug: "mbour", lat: 14.7333, lng: -17.05, description: "Commune abritant l'aéroport international Blaise-Diagne." },
  { name: "Fissel", slug: "fissel", departmentSlug: "mbour", lat: 14.3667, lng: -16.6833 },
  { name: "Malicounda", slug: "malicounda", departmentSlug: "mbour", lat: 14.4, lng: -16.9167 },
  { name: "Sandiara", slug: "sandiara", departmentSlug: "mbour", lat: 14.3, lng: -16.9667 },
  { name: "Sessène", slug: "sessene", departmentSlug: "mbour", lat: 14.2333, lng: -16.6167 },
  { name: "Sindia", slug: "sindia", departmentSlug: "mbour", lat: 14.5333, lng: -17.0 },
  // Thiès (département) — référentiel officiel, 15 communes (la ville de Thiès
  // est elle-même divisée en 3 communes : Thiès Est, Thiès Nord, Thiès Ouest)
  { name: "Ndieyène Sirakh", slug: "ndieyene-sirakh", departmentSlug: "thies-dept", lat: 14.7, lng: -16.85 },
  { name: "Ngoundiane", slug: "ngoundiane", departmentSlug: "thies-dept", lat: 14.6667, lng: -16.8 },
  { name: "Cayar", slug: "cayar", departmentSlug: "thies-dept", lat: 14.9167, lng: -17.1833, description: "Village de pêcheurs réputé sur la Grande Côte." },
  { name: "Khombole", slug: "khombole", departmentSlug: "thies-dept", lat: 14.7667, lng: -16.7 },
  { name: "Pout", slug: "pout", departmentSlug: "thies-dept", lat: 14.7667, lng: -17.0667 },
  { name: "Diender Guedji", slug: "diender-guedji", departmentSlug: "thies-dept", lat: 14.85, lng: -17.0833 },
  { name: "Fandène", slug: "fandene", departmentSlug: "thies-dept", lat: 14.8333, lng: -16.9667 },
  { name: "Keur Moussa", slug: "keur-moussa", departmentSlug: "thies-dept", lat: 14.8167, lng: -17.0167 },
  { name: "Notto", slug: "notto", departmentSlug: "thies-dept", lat: 14.85, lng: -16.9167 },
  { name: "Tassette", slug: "tassette", departmentSlug: "thies-dept", lat: 14.8167, lng: -16.8333 },
  { name: "Thiénaba", slug: "thienaba", departmentSlug: "thies-dept", lat: 14.7167, lng: -16.8167 },
  { name: "Thiès Est", slug: "thies-est", departmentSlug: "thies-dept", lat: 14.8, lng: -16.92, population: 130000, description: "Troisième ville du pays, carrefour ferroviaire et industriel historique." },
  { name: "Thiès Nord", slug: "thies-nord", departmentSlug: "thies-dept", lat: 14.8, lng: -16.94, population: 110000 },
  { name: "Thiès Ouest", slug: "thies-ouest", departmentSlug: "thies-dept", lat: 14.79, lng: -16.95, population: 100000 },
  { name: "Touba Toul", slug: "touba-toul", departmentSlug: "thies-dept", lat: 14.7167, lng: -16.7667 },
  // Tivaouane (département) — référentiel officiel, 18 communes
  { name: "Ngandiouf", slug: "ngandiouf", departmentSlug: "tivaouane", lat: 15.0333, lng: -16.7 },
  { name: "Chérif Lô", slug: "cherif-lo", departmentSlug: "tivaouane", lat: 15.0667, lng: -16.6333 },
  { name: "Mboro", slug: "mboro", departmentSlug: "tivaouane", lat: 15.15, lng: -17.0167, description: "Pôle d'extraction minière de phosphates sur la Grande Côte." },
  { name: "Mékhé", slug: "mekhe", departmentSlug: "tivaouane", lat: 15.1167, lng: -16.6167 },
  { name: "Tivaouane", slug: "tivaouane", departmentSlug: "tivaouane", lat: 14.95, lng: -16.8167, population: 70000, description: "Haut lieu religieux, siège du grand magal des Tidianes." },
  { name: "Darou Khoudoss", slug: "darou-khoudoss", departmentSlug: "tivaouane", lat: 15.0167, lng: -16.9333 },
  { name: "Koul", slug: "koul", departmentSlug: "tivaouane", lat: 14.9333, lng: -16.7 },
  { name: "Mbayène", slug: "mbayene", departmentSlug: "tivaouane", lat: 14.9667, lng: -16.65 },
  { name: "Méouane", slug: "meouane", departmentSlug: "tivaouane", lat: 15.0833, lng: -16.75 },
  { name: "Mérina Dakhar", slug: "merina-dakhar", departmentSlug: "tivaouane", lat: 15.1833, lng: -16.55 },
  { name: "Mont-Rolland", slug: "mont-rolland", departmentSlug: "tivaouane", lat: 14.9333, lng: -16.8833 },
  { name: "Niakhène", slug: "niakhene", departmentSlug: "tivaouane", lat: 15.05, lng: -16.5833 },
  { name: "Notto Gouye Diama", slug: "notto-gouye-diama", departmentSlug: "tivaouane", lat: 14.9833, lng: -17.0 },
  { name: "Pambal", slug: "pambal", departmentSlug: "tivaouane", lat: 15.05, lng: -16.8833 },
  { name: "Pékèsse", slug: "pekesse", departmentSlug: "tivaouane", lat: 14.9833, lng: -16.6833 },
  { name: "Pire Goureye", slug: "pire-goureye", departmentSlug: "tivaouane", lat: 15.15, lng: -16.45 },
  { name: "Taïba Ndiaye", slug: "taiba-ndiaye", departmentSlug: "tivaouane", lat: 15.1167, lng: -16.85, description: "Commune accueillant le plus grand parc éolien d'Afrique de l'Ouest." },
  { name: "Thilmakha", slug: "thilmakha", departmentSlug: "tivaouane", lat: 15.0167, lng: -16.6 },
  // Bambey (département) — référentiel officiel, 12 communes (population : recensement 2023)
  { name: "Baba Garage", slug: "baba-garage", departmentSlug: "bambey", lat: 14.75, lng: -16.35, population: 18305 },
  { name: "Bambey", slug: "bambey", departmentSlug: "bambey", lat: 14.6961, lng: -16.4486, population: 37374 },
  { name: "Dinguiraye", slug: "dinguiraye-bambey", departmentSlug: "bambey", lat: 14.65, lng: -16.5, population: 11881 },
  { name: "Keur Samba Kané", slug: "keur-samba-kane", departmentSlug: "bambey", lat: 14.8, lng: -16.4, population: 21036 },
  { name: "Gawane", slug: "gawane", departmentSlug: "bambey", lat: 14.7, lng: -16.3, population: 19907 },
  { name: "Lambaye", slug: "lambaye", departmentSlug: "bambey", lat: 14.95, lng: -16.55, population: 30486, description: "Ancienne capitale du royaume du Baol." },
  { name: "Ngogom", slug: "ngogom", departmentSlug: "bambey", lat: 14.6, lng: -16.35, population: 40948 },
  { name: "Réfane", slug: "refane", departmentSlug: "bambey", lat: 14.85, lng: -16.6, population: 39955 },
  { name: "Dangalma", slug: "dangalma", departmentSlug: "bambey", lat: 14.55, lng: -16.4, population: 44398 },
  { name: "Ndondol", slug: "ndondol", departmentSlug: "bambey", lat: 14.6, lng: -16.55, population: 25843 },
  { name: "Ngoye", slug: "ngoye", departmentSlug: "bambey", lat: 14.65, lng: -16.6, population: 54238 },
  { name: "Thiakar", slug: "thiakar", departmentSlug: "bambey", lat: 14.75, lng: -16.55, population: 32096 },
  // Diourbel (département) — référentiel officiel, 12 communes (population : recensement 2023)
  { name: "Diourbel", slug: "diourbel", departmentSlug: "diourbel-dept", lat: 14.6552, lng: -16.2342, population: 157554 },
  { name: "Dankh Sène", slug: "dankh-sene", departmentSlug: "diourbel-dept", lat: 14.7, lng: -16.15, population: 12410 },
  { name: "Gadé Escale", slug: "gade-escale", departmentSlug: "diourbel-dept", lat: 14.6, lng: -16.1, population: 4521 },
  { name: "Ndindy", slug: "ndindy", departmentSlug: "diourbel-dept", lat: 14.75, lng: -16.2, population: 17326 },
  { name: "Keur Ngalgou", slug: "keur-ngalgou", departmentSlug: "diourbel-dept", lat: 14.6, lng: -16.25, population: 9760 },
  { name: "Taïba Moutoupha", slug: "taiba-moutoupha", departmentSlug: "diourbel-dept", lat: 14.55, lng: -16.15, population: 13890 },
  { name: "Touba Lappé", slug: "touba-lappe", departmentSlug: "diourbel-dept", lat: 14.8, lng: -16.25, population: 5127 },
  { name: "Ndoulo", slug: "ndoulo", departmentSlug: "diourbel-dept", lat: 14.7, lng: -16.3, population: 14820 },
  { name: "Ngohé", slug: "ngohe", departmentSlug: "diourbel-dept", lat: 14.55, lng: -16.3, population: 40758 },
  { name: "Patar", slug: "patar-diourbel", departmentSlug: "diourbel-dept", lat: 14.5, lng: -16.2, population: 26656 },
  { name: "Tocky Garé", slug: "tocky-gare", departmentSlug: "diourbel-dept", lat: 14.65, lng: -16.1, population: 24821 },
  { name: "Touré Mbonde", slug: "toure-mbonde", departmentSlug: "diourbel-dept", lat: 14.5, lng: -16.1, population: 16466 },
  // Mbacké (département) — référentiel officiel, 16 communes (population : recensement 2023)
  { name: "Mbacké", slug: "mbacke", departmentSlug: "mbacke", lat: 14.7917, lng: -15.9083, population: 101451 },
  { name: "Dendéye Gouye Gui", slug: "dendeye-gouye-gui", departmentSlug: "mbacke", lat: 14.85, lng: -15.95, population: 7061 },
  { name: "Darou Salam Typ", slug: "darou-salam-typ", departmentSlug: "mbacke", lat: 14.95, lng: -15.9, population: 7245 },
  { name: "Kael", slug: "kael", departmentSlug: "mbacke", lat: 14.75, lng: -15.85, population: 7144 },
  { name: "Madina", slug: "madina-mbacke", departmentSlug: "mbacke", lat: 14.8, lng: -15.95, population: 8763 },
  { name: "Ndioumane T. Thiékène", slug: "ndioumane-t-thiekene", departmentSlug: "mbacke", lat: 14.9, lng: -15.85, population: 6651 },
  { name: "Touba Mboul", slug: "touba-mboul", departmentSlug: "mbacke", lat: 14.95, lng: -15.8, population: 13231 },
  { name: "Darou Nahim", slug: "darou-nahim", departmentSlug: "mbacke", lat: 14.7, lng: -15.9, population: 2942 },
  { name: "Taïba Tiéckène", slug: "taiba-tieckene", departmentSlug: "mbacke", lat: 14.65, lng: -15.85, population: 2465 },
  { name: "Dalla Ngabou", slug: "dalla-ngabou", departmentSlug: "mbacke", lat: 14.9, lng: -15.75, population: 12609 },
  { name: "Missirah", slug: "missirah-mbacke", departmentSlug: "mbacke", lat: 14.95, lng: -15.7, population: 8416 },
  { name: "Nghaye", slug: "nghaye", departmentSlug: "mbacke", lat: 14.7, lng: -15.8, population: 6777 },
  { name: "Touba Fall", slug: "touba-fall", departmentSlug: "mbacke", lat: 14.85, lng: -15.75, population: 11500 },
  { name: "Touba Mosquée", slug: "touba", departmentSlug: "mbacke", lat: 14.85, lng: -15.8833, population: 1120824, description: "Capitale spirituelle de la confrérie mouride, siège du grand Magal et de la Grande Mosquée." },
  { name: "Sadio", slug: "sadio", departmentSlug: "mbacke", lat: 14.6, lng: -15.95, population: 24444 },
  { name: "Taïf", slug: "taif", departmentSlug: "mbacke", lat: 14.65, lng: -15.95, population: 18233 },
  // Fatick (département) — référentiel officiel, 17 communes
  { name: "Diakhao", slug: "diakhao", departmentSlug: "fatick-dept", lat: 14.3667, lng: -16.3167 },
  { name: "Diofior", slug: "diofior", departmentSlug: "fatick-dept", lat: 14.1833, lng: -16.65 },
  { name: "Fatick", slug: "fatick", departmentSlug: "fatick-dept", lat: 14.339, lng: -16.411, population: 33000 },
  { name: "Diaoulé", slug: "diaoule", departmentSlug: "fatick-dept", lat: 14.2167, lng: -16.4833 },
  { name: "Diarère", slug: "diarere", departmentSlug: "fatick-dept", lat: 14.2667, lng: -16.35 },
  { name: "Diouroup", slug: "diouroup", departmentSlug: "fatick-dept", lat: 14.1167, lng: -16.5833 },
  { name: "Djilasse", slug: "djilasse", departmentSlug: "fatick-dept", lat: 14.2333, lng: -16.5167 },
  { name: "Fimela", slug: "fimela", departmentSlug: "fatick-dept", lat: 14.0167, lng: -16.55 },
  { name: "Loul-Sessène", slug: "loul-sessene", departmentSlug: "fatick-dept", lat: 14.15, lng: -16.45 },
  { name: "Mbélacadiao", slug: "mbelacadiao", departmentSlug: "fatick-dept", lat: 14.4167, lng: -16.3667 },
  { name: "Ndiob", slug: "ndiob", departmentSlug: "fatick-dept", lat: 14.2833, lng: -16.2667 },
  { name: "Ngayokhème", slug: "ngayokheme", departmentSlug: "fatick-dept", lat: 14.3667, lng: -16.2333 },
  { name: "Niakhar", slug: "niakhar", departmentSlug: "fatick-dept", lat: 14.4833, lng: -16.4167 },
  { name: "Palmarin Facao", slug: "palmarin-facao", departmentSlug: "fatick-dept", lat: 13.9833, lng: -16.6833, description: "Village touristique réputé pour ses lagunes et son écotourisme, sur la Petite Côte." },
  { name: "Patar", slug: "patar", departmentSlug: "fatick-dept", lat: 14.4333, lng: -16.45 },
  { name: "Tattaguine", slug: "tattaguine", departmentSlug: "fatick-dept", lat: 14.2333, lng: -16.1667 },
  { name: "Thiaré Ndialgui", slug: "thiare-ndialgui", departmentSlug: "fatick-dept", lat: 14.4, lng: -16.2833 },
  // Foundiougne (département) — référentiel officiel, 17 communes
  { name: "Bassoul", slug: "bassoul", departmentSlug: "foundiougne", lat: 13.85, lng: -16.6167 },
  { name: "Foundiougne", slug: "foundiougne", departmentSlug: "foundiougne", lat: 14.1333, lng: -16.4667, population: 8000 },
  { name: "Karang Poste", slug: "karang-poste", departmentSlug: "foundiougne", lat: 13.5, lng: -16.7167 },
  { name: "Passy", slug: "passy", departmentSlug: "foundiougne", lat: 14.05, lng: -16.3167 },
  { name: "Sokone", slug: "sokone", departmentSlug: "foundiougne", lat: 13.8833, lng: -16.3667 },
  { name: "Soum", slug: "soum", departmentSlug: "foundiougne", lat: 13.9667, lng: -16.2667 },
  { name: "Diagane Barka", slug: "diagane-barka", departmentSlug: "foundiougne", lat: 13.9333, lng: -16.4167 },
  { name: "Dionewar", slug: "dionewar", departmentSlug: "foundiougne", lat: 13.75, lng: -16.7167, description: "Île du delta du Saloum, économie tournée vers la pêche." },
  { name: "Diossong", slug: "diossong", departmentSlug: "foundiougne", lat: 14.0, lng: -16.45 },
  { name: "Djilor", slug: "djilor", departmentSlug: "foundiougne", lat: 14.0667, lng: -16.4333 },
  { name: "Djirnda", slug: "djirnda", departmentSlug: "foundiougne", lat: 13.8, lng: -16.65 },
  { name: "Keur Samba Gueye", slug: "keur-samba-gueye", departmentSlug: "foundiougne", lat: 13.9167, lng: -16.5333 },
  { name: "Keur Saloum Diane", slug: "keur-saloum-diane", departmentSlug: "foundiougne", lat: 13.8667, lng: -16.5 },
  { name: "Mbam", slug: "mbam", departmentSlug: "foundiougne", lat: 13.8333, lng: -16.4 },
  { name: "Niassène", slug: "niassene", departmentSlug: "foundiougne", lat: 14.0833, lng: -16.2333 },
  { name: "Nioro Alassane Tall", slug: "nioro-alassane-tall", departmentSlug: "foundiougne", lat: 13.8667, lng: -16.15 },
  { name: "Toubacouta", slug: "toubacouta", departmentSlug: "foundiougne", lat: 13.7833, lng: -16.45, description: "Porte d'entrée du delta du Saloum, écotourisme et réserve de Fathala." },
  // Gossas (département) — référentiel officiel, 6 communes
  { name: "Colobane", slug: "colobane", departmentSlug: "gossas", lat: 14.5333, lng: -15.9667 },
  { name: "Gossas", slug: "gossas", departmentSlug: "gossas", lat: 14.4944, lng: -16.0667, population: 12000 },
  { name: "Mbar", slug: "mbar", departmentSlug: "gossas", lat: 14.45, lng: -16.1167 },
  { name: "Ndiène Lagane", slug: "ndiene-lagane", departmentSlug: "gossas", lat: 14.5667, lng: -16.1333 },
  { name: "Ouadiour", slug: "ouadiour", departmentSlug: "gossas", lat: 14.4167, lng: -16.0167 },
  { name: "Patar Lia", slug: "patar-lia", departmentSlug: "gossas", lat: 14.5167, lng: -15.9833 },
  // Guinguinéo (département) — référentiel officiel, 12 communes
  { name: "Fass", slug: "fass", departmentSlug: "guinguineo", lat: 14.3, lng: -15.9 },
  { name: "Guinguinéo", slug: "guinguineo", departmentSlug: "guinguineo", lat: 14.2667, lng: -15.95, population: 22000 },
  { name: "Mboss", slug: "mboss", departmentSlug: "guinguineo", lat: 14.2, lng: -15.85 },
  { name: "Dara Mboss", slug: "dara-mboss", departmentSlug: "guinguineo", lat: 14.18, lng: -15.83 },
  { name: "Gagnick", slug: "gagnick", departmentSlug: "guinguineo", lat: 14.35, lng: -15.92 },
  { name: "Khelcom Birame", slug: "khelcom-birame", departmentSlug: "guinguineo", lat: 14.25, lng: -15.75 },
  { name: "Mbadakhoune", slug: "mbadakhoune", departmentSlug: "guinguineo", lat: 14.15, lng: -15.95 },
  { name: "Ndiago", slug: "ndiago", departmentSlug: "guinguineo", lat: 14.3, lng: -16.0 },
  { name: "Ngathie Naoudé", slug: "ngathie-naoude", departmentSlug: "guinguineo", lat: 14.22, lng: -16.02 },
  { name: "Nguelou", slug: "nguelou", departmentSlug: "guinguineo", lat: 14.27, lng: -15.88 },
  { name: "Ourour", slug: "ourour", departmentSlug: "guinguineo", lat: 14.1, lng: -15.9 },
  { name: "Panal Ouolof", slug: "panal-ouolof", departmentSlug: "guinguineo", lat: 14.35, lng: -16.05 },
  // Kaolack (département) — référentiel officiel, 14 communes
  { name: "Gandiaye", slug: "gandiaye", departmentSlug: "kaolack-dept", lat: 14.0833, lng: -16.0833 },
  { name: "Kahone", slug: "kahone", departmentSlug: "kaolack-dept", lat: 14.1167, lng: -16.0167 },
  { name: "Kaolack", slug: "kaolack", departmentSlug: "kaolack-dept", lat: 14.1612, lng: -16.0728, population: 230000, description: "Grand centre commercial du bassin arachidier." },
  { name: "Ndoffane", slug: "ndoffane", departmentSlug: "kaolack-dept", lat: 14.1167, lng: -15.9333 },
  { name: "Sibassor", slug: "sibassor", departmentSlug: "kaolack-dept", lat: 13.9667, lng: -16.0667 },
  { name: "Dya", slug: "dya", departmentSlug: "kaolack-dept", lat: 14.05, lng: -16.1667 },
  { name: "Keur Baka", slug: "keur-baka", departmentSlug: "kaolack-dept", lat: 14.0167, lng: -15.9833 },
  { name: "Keur Soce", slug: "keur-soce", departmentSlug: "kaolack-dept", lat: 13.9167, lng: -15.9167 },
  { name: "Latmingué", slug: "latmingue", departmentSlug: "kaolack-dept", lat: 14.0667, lng: -16.2667 },
  { name: "Ndiaffate", slug: "ndiaffate", departmentSlug: "kaolack-dept", lat: 14.0167, lng: -16.2 },
  { name: "Ndiébel", slug: "ndiebel", departmentSlug: "kaolack-dept", lat: 14.0833, lng: -16.1333 },
  { name: "Ndiédieng", slug: "ndiedieng", departmentSlug: "kaolack-dept", lat: 13.9833, lng: -16.0333 },
  { name: "Thiaré", slug: "thiare", departmentSlug: "kaolack-dept", lat: 14.0333, lng: -15.8667 },
  { name: "Thiomby", slug: "thiomby", departmentSlug: "kaolack-dept", lat: 14.1333, lng: -15.9667 },
  // Nioro du Rip (département) — référentiel officiel, 15 communes
  { name: "Keur Madiabel", slug: "keur-madiabel", departmentSlug: "nioro-du-rip", lat: 13.6833, lng: -15.75 },
  { name: "Nioro du Rip", slug: "nioro-du-rip", departmentSlug: "nioro-du-rip", lat: 13.75, lng: -15.8, population: 20000 },
  { name: "Dabaly", slug: "dabaly", departmentSlug: "nioro-du-rip", lat: 13.65, lng: -15.9 },
  { name: "Darou Salam", slug: "darou-salam-nioro", departmentSlug: "nioro-du-rip", lat: 13.6, lng: -15.7 },
  { name: "Gainte Kaye", slug: "gainte-kaye", departmentSlug: "nioro-du-rip", lat: 13.8333, lng: -15.7 },
  { name: "Keur Mandongo", slug: "keur-mandongo", departmentSlug: "nioro-du-rip", lat: 13.7167, lng: -15.65 },
  { name: "Kayemor", slug: "kayemor", departmentSlug: "nioro-du-rip", lat: 13.9167, lng: -15.8833 },
  { name: "Keur Maba Diakhou", slug: "keur-maba-diakhou", departmentSlug: "nioro-du-rip", lat: 13.6667, lng: -15.8333 },
  { name: "Médina Sabakh", slug: "medina-sabakh", departmentSlug: "nioro-du-rip", lat: 13.6333, lng: -15.5167 },
  { name: "Ndramé Escale", slug: "ndrame-escale", departmentSlug: "nioro-du-rip", lat: 13.8, lng: -15.9167 },
  { name: "Ngayène", slug: "ngayene", departmentSlug: "nioro-du-rip", lat: 13.7, lng: -15.6 },
  { name: "Paoskoto", slug: "paoskoto", departmentSlug: "nioro-du-rip", lat: 13.85, lng: -15.8 },
  { name: "Porokhane", slug: "porokhane", departmentSlug: "nioro-du-rip", lat: 13.6167, lng: -15.6833 },
  { name: "Taïba Niassène", slug: "taiba-niassene", departmentSlug: "nioro-du-rip", lat: 13.9, lng: -15.7333 },
  { name: "Wack Ngouna", slug: "wack-ngouna", departmentSlug: "nioro-du-rip", lat: 13.85, lng: -15.6167 },
  // Birkelane (département) — référentiel officiel, 8 communes
  { name: "Ndiognick", slug: "ndiognick", departmentSlug: "birkilane", lat: 14.15, lng: -15.65 },
  { name: "Birkilane", slug: "birkilane", departmentSlug: "birkilane", lat: 14.1167, lng: -15.7333, population: 10000 },
  { name: "Diamal", slug: "diamal", departmentSlug: "birkilane", lat: 14.2, lng: -15.8 },
  { name: "Keur M'Bouki", slug: "keur-mbouki", departmentSlug: "birkilane", lat: 14.05, lng: -15.7 },
  { name: "Mabo", slug: "mabo", departmentSlug: "birkilane", lat: 14.1, lng: -15.6 },
  { name: "Mbeuleup", slug: "mbeuleup", departmentSlug: "birkilane", lat: 14.18, lng: -15.75 },
  { name: "Segré Gatta", slug: "segre-gatta", departmentSlug: "birkilane", lat: 14.08, lng: -15.78 },
  { name: "Touba M'Bella", slug: "touba-mbella", departmentSlug: "birkilane", lat: 14.22, lng: -15.7 },
  // Kaffrine (département) — référentiel officiel, 9 communes
  { name: "Boulel", slug: "boulel", departmentSlug: "kaffrine-dept", lat: 14.05, lng: -15.45 },
  { name: "Nganda", slug: "nganda", departmentSlug: "kaffrine-dept", lat: 14.25, lng: -15.55 },
  { name: "Kaffrine", slug: "kaffrine", departmentSlug: "kaffrine-dept", lat: 14.1059, lng: -15.55, population: 50000 },
  { name: "Diamagadio", slug: "diamagadio", departmentSlug: "kaffrine-dept", lat: 14.0, lng: -15.6 },
  { name: "Diokoul M'Belbouck", slug: "diokoul-mbelbouck", departmentSlug: "kaffrine-dept", lat: 14.15, lng: -15.5 },
  { name: "Gniby", slug: "gniby", departmentSlug: "kaffrine-dept", lat: 13.95, lng: -15.55 },
  { name: "Kahi", slug: "kahi", departmentSlug: "kaffrine-dept", lat: 14.2, lng: -15.45 },
  { name: "Kathiote", slug: "kathiote", departmentSlug: "kaffrine-dept", lat: 14.1, lng: -15.4 },
  { name: "Médinatoul Salam 2", slug: "medinatoul-salam-2", departmentSlug: "kaffrine-dept", lat: 14.05, lng: -15.5 },
  // Koungheul (département) — référentiel officiel, 9 communes
  { name: "Koungheul", slug: "koungheul", departmentSlug: "koungheul", lat: 13.9833, lng: -14.8, population: 25000 },
  { name: "Fass Thiékéné", slug: "fass-thiekene", departmentSlug: "koungheul", lat: 14.05, lng: -14.85 },
  { name: "Gainthe Pathé", slug: "gainthe-pathe", departmentSlug: "koungheul", lat: 13.9, lng: -14.7 },
  { name: "Ida Mouride", slug: "ida-mouride", departmentSlug: "koungheul", lat: 13.95, lng: -14.65 },
  { name: "Lour Escale", slug: "lour-escale", departmentSlug: "koungheul", lat: 14.1, lng: -14.9 },
  { name: "Maka Yop", slug: "maka-yop", departmentSlug: "koungheul", lat: 13.85, lng: -14.8 },
  { name: "Missirah Wadène", slug: "missirah-wadene", departmentSlug: "koungheul", lat: 14.0, lng: -14.75 },
  { name: "Ribot Escale", slug: "ribot-escale", departmentSlug: "koungheul", lat: 13.92, lng: -14.85 },
  { name: "Saly Escale", slug: "saly-escale", departmentSlug: "koungheul", lat: 13.88, lng: -14.95 },
  // Malem Hodar (département) — référentiel officiel, 7 communes
  { name: "Ndioum Ngainth", slug: "ndioum-ngainth", departmentSlug: "malem-hodar", lat: 14.05, lng: -15.05 },
  { name: "Malem Hodar", slug: "malem-hodar", departmentSlug: "malem-hodar", lat: 14.0833, lng: -15.1167, population: 9000 },
  { name: "Darou Minam II", slug: "darou-minam-2", departmentSlug: "malem-hodar", lat: 14.15, lng: -15.15 },
  { name: "Dianke Souf", slug: "dianke-souf", departmentSlug: "malem-hodar", lat: 14.0, lng: -15.2 },
  { name: "Khelcom", slug: "khelcom-malem-hodar", departmentSlug: "malem-hodar", lat: 14.2, lng: -15.2 },
  { name: "Ndiobène Samba Lamo", slug: "ndiobene-samba-lamo", departmentSlug: "malem-hodar", lat: 14.1, lng: -15.0 },
  { name: "Sagna", slug: "sagna", departmentSlug: "malem-hodar", lat: 13.95, lng: -15.1 },
  // Kébémer (département) — référentiel officiel, 19 communes
  { name: "Badégné Ouolof", slug: "badegne-ouolof", departmentSlug: "kebemer", lat: 15.45, lng: -16.4 },
  { name: "Guéoul", slug: "gueoul", departmentSlug: "kebemer", lat: 15.5167, lng: -16.3 },
  { name: "Kébémer", slug: "kebemer", departmentSlug: "kebemer", lat: 15.3833, lng: -16.45, population: 15000 },
  { name: "Darou Marnane", slug: "darou-marnane", departmentSlug: "kebemer", lat: 15.3, lng: -16.3 },
  { name: "Darou Mousty", slug: "darou-mousty", departmentSlug: "kebemer", lat: 15.15, lng: -16.4 },
  { name: "Diokoul Diawrigne", slug: "diokoul-diawrigne", departmentSlug: "kebemer", lat: 15.45, lng: -16.55 },
  { name: "Kab Gaye", slug: "kab-gaye", departmentSlug: "kebemer", lat: 15.3, lng: -16.55 },
  { name: "Kanène Ndiob", slug: "kanene-ndiob", departmentSlug: "kebemer", lat: 15.4, lng: -16.5 },
  { name: "Loro", slug: "loro", departmentSlug: "kebemer", lat: 15.35, lng: -16.6 },
  { name: "Mbacké Cadior", slug: "mbacke-cadior", departmentSlug: "kebemer", lat: 15.25, lng: -16.5 },
  { name: "Mbadiane", slug: "mbadiane", departmentSlug: "kebemer", lat: 15.5, lng: -16.45 },
  { name: "Ndande", slug: "ndande", departmentSlug: "kebemer", lat: 15.5, lng: -16.6 },
  { name: "Ndoyène", slug: "ndoyene", departmentSlug: "kebemer", lat: 15.2, lng: -16.45 },
  { name: "Ngourane Ouolof", slug: "ngourane-ouolof", departmentSlug: "kebemer", lat: 15.55, lng: -16.5 },
  { name: "Sagatta Guèth", slug: "sagatta-gueth", departmentSlug: "kebemer", lat: 15.4, lng: -16.35 },
  { name: "Sam Yabal", slug: "sam-yabal", departmentSlug: "kebemer", lat: 15.3, lng: -16.45 },
  { name: "Thieppe", slug: "thieppe", departmentSlug: "kebemer", lat: 15.45, lng: -16.3 },
  { name: "Thiolom Fall", slug: "thiolom-fall", departmentSlug: "kebemer", lat: 15.25, lng: -16.35 },
  { name: "Touba Mérina", slug: "touba-merina", departmentSlug: "kebemer", lat: 15.35, lng: -16.5 },
  // Linguère (département) — référentiel officiel, 19 communes
  { name: "Affé Djoloff", slug: "affe-djoloff", departmentSlug: "linguere", lat: 15.55, lng: -15.3 },
  { name: "Barkédji", slug: "barkedji", departmentSlug: "linguere", lat: 15.27, lng: -14.88 },
  { name: "Boulal", slug: "boulal", departmentSlug: "linguere", lat: 15.7, lng: -15.05 },
  { name: "Dahra", slug: "dahra", departmentSlug: "linguere", lat: 15.35, lng: -15.48, description: "Importante place commerciale du Djoloff, célèbre pour son marché au bétail." },
  { name: "Linguère", slug: "linguere", departmentSlug: "linguere", lat: 15.3939, lng: -15.1186, population: 20000 },
  { name: "Mbeuleukhé", slug: "mbeuleukhe", departmentSlug: "linguere", lat: 15.45, lng: -14.9 },
  { name: "Déali", slug: "deali", departmentSlug: "linguere", lat: 15.5, lng: -15.2 },
  { name: "Dodji", slug: "dodji", departmentSlug: "linguere", lat: 15.6, lng: -15.15 },
  { name: "Gassane", slug: "gassane", departmentSlug: "linguere", lat: 15.2, lng: -14.95 },
  { name: "Kamb", slug: "kamb", departmentSlug: "linguere", lat: 15.65, lng: -15.35 },
  { name: "Labgar", slug: "labgar", departmentSlug: "linguere", lat: 15.8, lng: -15.2 },
  { name: "Mboula", slug: "mboula", departmentSlug: "linguere", lat: 15.3, lng: -14.95 },
  { name: "Ouarkhokh", slug: "ouarkhokh", departmentSlug: "linguere", lat: 15.45, lng: -15.55 },
  { name: "Sagatta Djolof", slug: "sagatta-djolof", departmentSlug: "linguere", lat: 15.55, lng: -15.1 },
  { name: "Tessékré Forage", slug: "tessekre-forage", departmentSlug: "linguere", lat: 15.9, lng: -15.1 },
  { name: "Thiamène Djolof", slug: "thiamene-djolof", departmentSlug: "linguere", lat: 15.4, lng: -15.3 },
  { name: "Thiargny", slug: "thiargny", departmentSlug: "linguere", lat: 15.25, lng: -15.05 },
  { name: "Thiel", slug: "thiel", departmentSlug: "linguere", lat: 15.6, lng: -15.45 },
  { name: "Yang Yang", slug: "yang-yang", departmentSlug: "linguere", lat: 15.95, lng: -15.15 },
  // Louga (département) — référentiel officiel, 17 communes
  { name: "Coki", slug: "coki", departmentSlug: "louga-dept", lat: 15.65, lng: -16.05 },
  { name: "Louga", slug: "louga", departmentSlug: "louga-dept", lat: 15.6173, lng: -16.224, population: 150000 },
  { name: "Ndiagne", slug: "ndiagne", departmentSlug: "louga-dept", lat: 15.75, lng: -16.3 },
  { name: "Gande", slug: "gande", departmentSlug: "louga-dept", lat: 15.5, lng: -16.1 },
  { name: "Guet Ardo", slug: "guet-ardo", departmentSlug: "louga-dept", lat: 15.85, lng: -16.1 },
  { name: "Keur Momar Sarr", slug: "keur-momar-sarr", departmentSlug: "louga-dept", lat: 15.95, lng: -16.05, description: "Site de la station de pompage d'eau du Lac de Guiers alimentant Dakar." },
  { name: "Kelle Gueye", slug: "kelle-gueye", departmentSlug: "louga-dept", lat: 15.55, lng: -16.3 },
  { name: "Léona", slug: "leona", departmentSlug: "louga-dept", lat: 15.6, lng: -16.18 },
  { name: "Mbédiène", slug: "mbediene", departmentSlug: "louga-dept", lat: 15.45, lng: -16.2 },
  { name: "Nguer Malal", slug: "nguer-malal", departmentSlug: "louga-dept", lat: 15.7, lng: -16.15 },
  { name: "Nguéune Sarr", slug: "ngueune-sarr", departmentSlug: "louga-dept", lat: 15.8, lng: -16.2 },
  { name: "Nguidilé", slug: "nguidile", departmentSlug: "louga-dept", lat: 15.55, lng: -16.05 },
  { name: "Niomré", slug: "niomre", departmentSlug: "louga-dept", lat: 15.7, lng: -16.05 },
  { name: "Pété Ouarack", slug: "pete-ouarack", departmentSlug: "louga-dept", lat: 15.5, lng: -16.05 },
  { name: "Sakal", slug: "sakal", departmentSlug: "louga-dept", lat: 15.85, lng: -16.35 },
  { name: "Syer", slug: "syer", departmentSlug: "louga-dept", lat: 15.7, lng: -16.35 },
  { name: "Thiamène Cayor", slug: "thiamene-cayor", departmentSlug: "louga-dept", lat: 15.5, lng: -16.3 },
  // Dagana (département) — référentiel officiel, 11 communes (population : recensement 2023)
  { name: "Dagana", slug: "dagana", departmentSlug: "dagana", lat: 16.5167, lng: -15.5, population: 26568 },
  { name: "Richard-Toll", slug: "richard-toll", departmentSlug: "dagana", lat: 16.4625, lng: -15.7, population: 73147 },
  { name: "Mbane", slug: "mbane", departmentSlug: "dagana", lat: 16.2, lng: -15.85, population: 40754 },
  { name: "Bokhol", slug: "bokhol", departmentSlug: "dagana", lat: 16.35, lng: -15.55, population: 22651 },
  { name: "Gaé", slug: "gae", departmentSlug: "dagana", lat: 16.15, lng: -15.95, population: 12296 },
  { name: "Ndombo Sandjiry", slug: "ndombo-sandjiry", departmentSlug: "dagana", lat: 16.1, lng: -16.05, population: 6180 },
  { name: "Diama", slug: "diama", departmentSlug: "dagana", lat: 16.3, lng: -16.3, population: 48498, description: "Commune du barrage anti-sel de Diama, à l'embouchure du fleuve Sénégal." },
  { name: "Ngnith", slug: "ngnith", departmentSlug: "dagana", lat: 16.05, lng: -16.15, population: 32709 },
  { name: "Ronkh", slug: "ronkh", departmentSlug: "dagana", lat: 16.2, lng: -16.2, population: 27736 },
  { name: "Ross-Béthio", slug: "ross-bethio", departmentSlug: "dagana", lat: 16.2667, lng: -16.2667, population: 16225 },
  { name: "Rosso-Sénégal", slug: "rosso-senegal", departmentSlug: "dagana", lat: 16.5, lng: -15.8, population: 22299, description: "Poste frontalier face à Rosso, en Mauritanie, de l'autre côté du fleuve Sénégal." },
  // Podor (département) — référentiel officiel, 22 communes (population : recensement 2023)
  { name: "Podor", slug: "podor", departmentSlug: "podor", lat: 16.65, lng: -14.9667, population: 12512 },
  { name: "Ndioum", slug: "ndioum", departmentSlug: "podor", lat: 16.5167, lng: -14.65, population: 20270 },
  { name: "Médina Ndiathbé", slug: "medina-ndiathbe", departmentSlug: "podor", lat: 16.45, lng: -14.55, population: 41491 },
  { name: "Dounga-Lao", slug: "dounga-lao", departmentSlug: "podor", lat: 16.3, lng: -14.35, population: 43611 },
  { name: "Méry", slug: "mery", departmentSlug: "podor", lat: 16.4, lng: -14.4, population: 22731 },
  { name: "Aéré Lao", slug: "aere-lao", departmentSlug: "podor", lat: 16.25, lng: -14.2, population: 14384 },
  { name: "Golléré", slug: "gollere", departmentSlug: "podor", lat: 16.2, lng: -14.1, population: 7124 },
  { name: "Mboumba", slug: "mboumba", departmentSlug: "podor", lat: 16.55, lng: -14.75, population: 5457 },
  { name: "Walaldé", slug: "walalde", departmentSlug: "podor", lat: 16.6, lng: -14.85, population: 4387 },
  { name: "Boké Diallouvé", slug: "boke-diallouve", departmentSlug: "podor", lat: 16.1, lng: -13.95, population: 39506 },
  { name: "Mbolo Birane", slug: "mbolo-birane", departmentSlug: "podor", lat: 16.05, lng: -14.0, population: 31102 },
  { name: "Galoya Toucouleur", slug: "galoya-toucouleur", departmentSlug: "podor", lat: 16.15, lng: -14.05, population: 6501 },
  { name: "Pété", slug: "pete", departmentSlug: "podor", lat: 16.0, lng: -13.9, population: 4835 },
  { name: "Fanaye", slug: "fanaye", departmentSlug: "podor", lat: 16.55, lng: -15.2, population: 48174 },
  { name: "Ndiayène Pendao", slug: "ndiayene-pendao", departmentSlug: "podor", lat: 16.6, lng: -15.1, population: 34012 },
  { name: "Ndiandane", slug: "ndiandane", departmentSlug: "podor", lat: 16.5, lng: -15.05, population: 6769 },
  { name: "Dodel", slug: "dodel", departmentSlug: "podor", lat: 16.3, lng: -14.5, population: 46316 },
  { name: "Gamadji Saré", slug: "gamadji-sare", departmentSlug: "podor", lat: 16.25, lng: -14.55, population: 29971 },
  { name: "Guédé Village", slug: "guede-village", departmentSlug: "podor", lat: 16.35, lng: -14.6, population: 52678 },
  { name: "Bodé Lao", slug: "bode-lao", departmentSlug: "podor", lat: 16.2, lng: -14.45, population: 3760 },
  { name: "Demette", slug: "demette", departmentSlug: "podor", lat: 16.15, lng: -14.5, population: 3414 },
  { name: "Guédé Chantier", slug: "guede-chantier", departmentSlug: "podor", lat: 16.3, lng: -14.65, population: 7002 },
  // Saint-Louis (département) — référentiel officiel, 5 communes (population : recensement 2023)
  { name: "Saint-Louis", slug: "saint-louis", departmentSlug: "saint-louis-dept", lat: 16.0179, lng: -16.4896, population: 254171, description: "Ancienne capitale de l'AOF, ville classée patrimoine mondial de l'UNESCO." },
  { name: "Gandon", slug: "gandon", departmentSlug: "saint-louis-dept", lat: 15.95, lng: -16.4, population: 71080 },
  { name: "Fass Ngom", slug: "fass-ngom", departmentSlug: "saint-louis-dept", lat: 16.05, lng: -16.35, population: 23154 },
  { name: "Ndiébène Gandiole", slug: "ndiebene-gandiole", departmentSlug: "saint-louis-dept", lat: 15.9, lng: -16.45, population: 27938 },
  { name: "M'Pal", slug: "mpal", departmentSlug: "saint-louis-dept", lat: 15.95, lng: -16.3, population: 11025 },
  // Kanel (département) — référentiel officiel, 12 communes
  { name: "Aouré", slug: "aoure", departmentSlug: "kanel", lat: 15.55, lng: -13.05 },
  { name: "Bokiladji", slug: "bokiladji", departmentSlug: "kanel", lat: 15.35, lng: -13.35 },
  { name: "Dembancane", slug: "dembancane", departmentSlug: "kanel", lat: 16.1, lng: -13.65 },
  { name: "Hamady Ounaré", slug: "hamady-ounare", departmentSlug: "kanel", lat: 15.6, lng: -13.2 },
  { name: "Kanel", slug: "kanel", departmentSlug: "kanel", lat: 15.4944, lng: -13.1758, population: 15000 },
  { name: "Odobéré", slug: "odobere", departmentSlug: "kanel", lat: 16.05, lng: -13.5 },
  { name: "Sémmé", slug: "semme", departmentSlug: "kanel", lat: 15.3, lng: -13.0 },
  { name: "Sinthiou Bamambé-Banadji", slug: "sinthiou-bamambe-banadji", departmentSlug: "kanel", lat: 15.45, lng: -13.25 },
  { name: "Waoundé", slug: "waounde", departmentSlug: "kanel", lat: 15.65, lng: -13.3 },
  { name: "Ndendory", slug: "ndendory", departmentSlug: "kanel", lat: 15.4, lng: -13.1 },
  { name: "Orkadiéré", slug: "orkadiere", departmentSlug: "kanel", lat: 15.95, lng: -13.4 },
  { name: "Ouro Sidy", slug: "ouro-sidy", departmentSlug: "kanel", lat: 15.5, lng: -13.15 },
  // Matam (département) — référentiel officiel, 10 communes
  { name: "Agnam-Civol", slug: "agnam-civol", departmentSlug: "matam-dept", lat: 15.7, lng: -13.2 },
  { name: "Bokidiawé", slug: "bokidiawe", departmentSlug: "matam-dept", lat: 15.5, lng: -13.05 },
  { name: "Matam", slug: "matam", departmentSlug: "matam-dept", lat: 15.6559, lng: -13.2548, population: 30000 },
  { name: "Nguidilogne", slug: "nguidilogne", departmentSlug: "matam-dept", lat: 15.75, lng: -13.15 },
  { name: "Ourossogui", slug: "ourossogui", departmentSlug: "matam-dept", lat: 15.6167, lng: -13.32, description: "Important carrefour commercial du Fouta, en pleine expansion urbaine." },
  { name: "Thilogne", slug: "thilogne", departmentSlug: "matam-dept", lat: 15.9, lng: -13.7 },
  { name: "Dabia", slug: "dabia", departmentSlug: "matam-dept", lat: 15.55, lng: -13.1 },
  { name: "Nabadji-Civol", slug: "nabadji-civol", departmentSlug: "matam-dept", lat: 15.65, lng: -13.1 },
  { name: "Ogo", slug: "ogo", departmentSlug: "matam-dept", lat: 15.75, lng: -13.3 },
  { name: "Oréfondé", slug: "orefonde", departmentSlug: "matam-dept", lat: 15.85, lng: -13.3 },
  // Ranérou Ferlo (département) — référentiel officiel, 4 communes
  { name: "Ranérou", slug: "ranerou", departmentSlug: "ranerou-ferlo", lat: 15.3, lng: -13.9667, population: 7000 },
  { name: "Lougré-Thioly", slug: "lougre-thioly", departmentSlug: "ranerou-ferlo", lat: 15.2, lng: -14.15 },
  { name: "Oudalaye", slug: "oudalaye", departmentSlug: "ranerou-ferlo", lat: 15.45, lng: -13.85 },
  // Note : homonyme de "Vélingara" (commune chef-lieu du département de Vélingara,
  // région de Kolda) ; nommée "Vélingara Ferlo" ici pour éviter le doublon de slug.
  { name: "Vélingara Ferlo", slug: "velingara-ferlo", departmentSlug: "ranerou-ferlo", lat: 15.1, lng: -14.05 },
  // Bakel (département) — référentiel officiel, 12 communes
  { name: "Ballou", slug: "ballou", departmentSlug: "bakel", lat: 14.8, lng: -12.3 },
  { name: "Bélé", slug: "bele", departmentSlug: "bakel", lat: 14.95, lng: -12.3 },
  { name: "Kidira", slug: "kidira", departmentSlug: "bakel", lat: 14.4667, lng: -12.2167, description: "Poste frontalier majeur avec le Mali, sur la voie ferrée Dakar-Bamako." },
  { name: "Bakel", slug: "bakel", departmentSlug: "bakel", lat: 14.9, lng: -12.4667, population: 12000 },
  { name: "Diawara", slug: "diawara", departmentSlug: "bakel", lat: 15.1, lng: -12.5 },
  { name: "Gabou", slug: "gabou", departmentSlug: "bakel", lat: 14.7, lng: -12.3 },
  { name: "Gathiary", slug: "gathiary", departmentSlug: "bakel", lat: 14.85, lng: -12.2 },
  { name: "Madina Foulbé", slug: "madina-foulbe", departmentSlug: "bakel", lat: 14.75, lng: -12.45 },
  { name: "Moudéry", slug: "moudery", departmentSlug: "bakel", lat: 14.95, lng: -12.6 },
  { name: "Sadatou", slug: "sadatou", departmentSlug: "bakel", lat: 14.6, lng: -12.4 },
  { name: "Sinthiou-Fissa", slug: "sinthiou-fissa", departmentSlug: "bakel", lat: 14.8, lng: -12.55 },
  { name: "Toumboura", slug: "toumboura", departmentSlug: "bakel", lat: 14.65, lng: -12.2 },
  // Goudiry (département) — référentiel officiel, 15 communes
  { name: "Bala", slug: "bala", departmentSlug: "goudiry", lat: 14.25, lng: -12.55 },
  { name: "Bani Israël", slug: "bani-israel", departmentSlug: "goudiry", lat: 14.05, lng: -12.85 },
  { name: "Boutoucoufara", slug: "boutoucoufara", departmentSlug: "goudiry", lat: 14.3, lng: -12.8 },
  { name: "Boynguel Bamba", slug: "boynguel-bamba", departmentSlug: "goudiry", lat: 14.1, lng: -12.6 },
  { name: "Goudiry", slug: "goudiry", departmentSlug: "goudiry", lat: 14.1833, lng: -12.7167, population: 9000 },
  { name: "Kothiary", slug: "kothiary", departmentSlug: "goudiry", lat: 14.35, lng: -12.65 },
  { name: "Dianke Makha", slug: "dianke-makha", departmentSlug: "goudiry", lat: 14.4, lng: -12.5 },
  { name: "Dougué", slug: "dougue", departmentSlug: "goudiry", lat: 14.0, lng: -12.7 },
  { name: "Goumbayel", slug: "goumbayel", departmentSlug: "goudiry", lat: 14.2, lng: -12.9 },
  { name: "Koar", slug: "koar", departmentSlug: "goudiry", lat: 14.45, lng: -12.75 },
  { name: "Komoti", slug: "komoti", departmentSlug: "goudiry", lat: 14.15, lng: -12.55 },
  { name: "Koulor", slug: "koulor", departmentSlug: "goudiry", lat: 13.95, lng: -12.6 },
  { name: "Koussan", slug: "koussan", departmentSlug: "goudiry", lat: 14.3, lng: -13.0 },
  { name: "Sinthiou Bocar Ali", slug: "sinthiou-bocar-ali", departmentSlug: "goudiry", lat: 14.1, lng: -12.75 },
  { name: "Sinthiou Mamadou Boubou", slug: "sinthiou-mamadou-boubou", departmentSlug: "goudiry", lat: 14.25, lng: -12.85 },
  // Koumpentoum (département) — référentiel officiel, 10 communes
  { name: "Ndame", slug: "ndame", departmentSlug: "koumpentoum", lat: 14.05, lng: -14.45 },
  { name: "Bamba Thialène", slug: "bamba-thialene", departmentSlug: "koumpentoum", lat: 13.9, lng: -14.7 },
  { name: "Koumpentoum", slug: "koumpentoum", departmentSlug: "koumpentoum", lat: 13.9833, lng: -14.5667, population: 14000 },
  { name: "Malem Niani", slug: "malem-niani", departmentSlug: "koumpentoum", lat: 13.85, lng: -14.55 },
  { name: "Kahène", slug: "kahene", departmentSlug: "koumpentoum", lat: 14.1, lng: -14.65 },
  { name: "Kouthia Gaydi", slug: "kouthia-gaydi", departmentSlug: "koumpentoum", lat: 13.95, lng: -14.4 },
  { name: "Kouthiaba Wolof", slug: "kouthiaba-wolof", departmentSlug: "koumpentoum", lat: 14.0, lng: -14.75 },
  { name: "Méréto", slug: "mereto", departmentSlug: "koumpentoum", lat: 13.8, lng: -14.45 },
  { name: "Pass Koto", slug: "pass-koto", departmentSlug: "koumpentoum", lat: 13.9, lng: -14.5 },
  { name: "Payar", slug: "payar", departmentSlug: "koumpentoum", lat: 14.05, lng: -14.6 },
  // Tambacounda (département) — référentiel officiel, 9 communes
  { name: "Ndoga Babacar", slug: "ndoga-babacar", departmentSlug: "tambacounda-dept", lat: 13.7, lng: -13.4 },
  { name: "Tambacounda", slug: "tambacounda", departmentSlug: "tambacounda-dept", lat: 13.7707, lng: -13.6673, population: 110000 },
  { name: "Dialacoto", slug: "dialacoto", departmentSlug: "tambacounda-dept", lat: 13.5, lng: -13.2 },
  { name: "Koussanar", slug: "koussanar", departmentSlug: "tambacounda-dept", lat: 13.95, lng: -14.2 },
  { name: "Makacoulibantang", slug: "makacoulibantang", departmentSlug: "tambacounda-dept", lat: 13.65, lng: -13.9 },
  { name: "Missirah", slug: "missirah-tambacounda", departmentSlug: "tambacounda-dept", lat: 13.55, lng: -13.6 },
  { name: "Nétéboulou", slug: "neteboulou", departmentSlug: "tambacounda-dept", lat: 13.85, lng: -13.5 },
  { name: "Niani Toucouleur", slug: "niani-toucouleur", departmentSlug: "tambacounda-dept", lat: 13.5, lng: -13.7 },
  { name: "Sinthiou Malem", slug: "sinthiou-malem", departmentSlug: "tambacounda-dept", lat: 13.65, lng: -13.55 },
  // Kédougou (département) — référentiel officiel, 7 communes
  { name: "Bandafassi", slug: "bandafassi", departmentSlug: "kedougou-dept", lat: 12.5167, lng: -12.3167 },
  { name: "Kédougou", slug: "kedougou", departmentSlug: "kedougou-dept", lat: 12.5556, lng: -12.1746, population: 30000 },
  { name: "Dimboli", slug: "dimboli", departmentSlug: "kedougou-dept", lat: 12.45, lng: -12.0667 },
  { name: "Dindifelo", slug: "dindifelo", departmentSlug: "kedougou-dept", lat: 12.3667, lng: -12.3, description: "Commune connue pour ses chutes d'eau et sa réserve naturelle communautaire." },
  { name: "Fongolembi", slug: "fongolembi", departmentSlug: "kedougou-dept", lat: 12.7167, lng: -12.2333 },
  { name: "Ninéfécha", slug: "ninefecha", departmentSlug: "kedougou-dept", lat: 12.6833, lng: -12.05 },
  { name: "Tomboronkoto", slug: "tomboronkoto", departmentSlug: "kedougou-dept", lat: 12.8333, lng: -11.9667 },
  // Salémata (département) — référentiel officiel, 6 communes
  { name: "Salémata", slug: "salemata", departmentSlug: "salemata", lat: 12.6333, lng: -12.8, population: 6000 },
  { name: "Dakateli", slug: "dakateli", departmentSlug: "salemata", lat: 12.5833, lng: -12.7167 },
  { name: "Dar Salam", slug: "dar-salam-salemata", departmentSlug: "salemata", lat: 12.7, lng: -12.8667 },
  { name: "Ethiolo", slug: "ethiolo", departmentSlug: "salemata", lat: 12.55, lng: -12.6833 },
  { name: "Kévoye", slug: "kevoye", departmentSlug: "salemata", lat: 12.6833, lng: -12.75 },
  { name: "Oubadji", slug: "oubadji", departmentSlug: "salemata", lat: 12.5167, lng: -12.8333 },
  // Saraya (département) — référentiel officiel, 6 communes
  { name: "Bembou", slug: "bembou", departmentSlug: "saraya", lat: 12.7167, lng: -11.6167 },
  { name: "Saraya", slug: "saraya", departmentSlug: "saraya", lat: 12.8333, lng: -11.7833, population: 8000 },
  { name: "Khossanto", slug: "khossanto", departmentSlug: "saraya", lat: 13.05, lng: -11.7833 },
  { name: "Médina Baffé", slug: "medina-baffe", departmentSlug: "saraya", lat: 12.95, lng: -11.7 },
  { name: "Missirah Sirimana", slug: "missirah-sirimana", departmentSlug: "saraya", lat: 12.75, lng: -11.9167 },
  { name: "Sabodala", slug: "sabodala", departmentSlug: "saraya", lat: 13.0167, lng: -11.6167, description: "Site de la principale mine d'or industrielle du Sénégal." },
  // Kolda (département) — référentiel officiel, 15 communes
  { name: "Bagadadji", slug: "bagadadji", departmentSlug: "kolda-dept", lat: 12.8, lng: -14.85 },
  { name: "Dabo", slug: "dabo", departmentSlug: "kolda-dept", lat: 12.7, lng: -14.85 },
  { name: "Kolda", slug: "kolda", departmentSlug: "kolda-dept", lat: 12.8939, lng: -14.941, population: 80000 },
  { name: "Salikégné", slug: "salikegne", departmentSlug: "kolda-dept", lat: 13.0, lng: -14.9 },
  { name: "Saré Yoba Diéga", slug: "sare-yoba-diega", departmentSlug: "kolda-dept", lat: 12.95, lng: -15.0 },
  { name: "Coumbacara", slug: "coumbacara", departmentSlug: "kolda-dept", lat: 12.75, lng: -15.05 },
  { name: "Dialambéré", slug: "dialambere", departmentSlug: "kolda-dept", lat: 12.95, lng: -14.85 },
  { name: "Dioulacolon", slug: "dioulacolon", departmentSlug: "kolda-dept", lat: 13.05, lng: -14.95 },
  { name: "Guiro Yéro Bocar", slug: "guiro-yero-bocar", departmentSlug: "kolda-dept", lat: 12.85, lng: -14.8 },
  { name: "Mampatim", slug: "mampatim", departmentSlug: "kolda-dept", lat: 12.65, lng: -14.95 },
  { name: "Médina El Hadji", slug: "medina-el-hadji", departmentSlug: "kolda-dept", lat: 12.9, lng: -15.05 },
  { name: "Médina Chérif", slug: "medina-cherif", departmentSlug: "kolda-dept", lat: 13.0, lng: -14.75 },
  { name: "Saré Bidji", slug: "sare-bidji", departmentSlug: "kolda-dept", lat: 12.8, lng: -15.1 },
  { name: "Tankanto Escale", slug: "tankanto-escale", departmentSlug: "kolda-dept", lat: 12.7, lng: -15.0 },
  { name: "Thietty", slug: "thietty", departmentSlug: "kolda-dept", lat: 12.85, lng: -14.7 },
  // Médina Yoro Foulah (département) — référentiel officiel, 11 communes
  { name: "Badion", slug: "badion", departmentSlug: "medina-yoro-foulah", lat: 12.9, lng: -14.5 },
  { name: "Bignarabé", slug: "bignarabe", departmentSlug: "medina-yoro-foulah", lat: 13.1, lng: -14.55 },
  { name: "Bourouco", slug: "bourouco", departmentSlug: "medina-yoro-foulah", lat: 13.15, lng: -14.7 },
  { name: "Médina Yoro Foulah", slug: "medina-yoro-foulah", departmentSlug: "medina-yoro-foulah", lat: 13.05, lng: -14.6, population: 6000 },
  { name: "Pata", slug: "pata", departmentSlug: "medina-yoro-foulah", lat: 13.0, lng: -14.45 },
  { name: "Dinguiraye", slug: "dinguiraye", departmentSlug: "medina-yoro-foulah", lat: 12.95, lng: -14.55 },
  { name: "Fafacourou", slug: "fafacourou", departmentSlug: "medina-yoro-foulah", lat: 13.2, lng: -14.6 },
  { name: "Kéréwane", slug: "kerewane", departmentSlug: "medina-yoro-foulah", lat: 13.1, lng: -14.45 },
  { name: "Koulinto", slug: "koulinto", departmentSlug: "medina-yoro-foulah", lat: 12.85, lng: -14.6 },
  { name: "Ndorna", slug: "ndorna", departmentSlug: "medina-yoro-foulah", lat: 13.05, lng: -14.45 },
  { name: "Niaming", slug: "niaming", departmentSlug: "medina-yoro-foulah", lat: 13.15, lng: -14.5 },
  // Vélingara (département) — référentiel officiel, 14 communes
  { name: "Bonconto", slug: "bonconto", departmentSlug: "velingara", lat: 13.05, lng: -14.0 },
  { name: "Diaoubé-Kabendou", slug: "diaoube-kabendou", departmentSlug: "velingara", lat: 13.3, lng: -14.1 },
  { name: "Kounkané", slug: "kounkane", departmentSlug: "velingara", lat: 13.25, lng: -14.2 },
  { name: "Vélingara", slug: "velingara", departmentSlug: "velingara", lat: 13.15, lng: -14.1167, population: 35000 },
  { name: "Kandia", slug: "kandia", departmentSlug: "velingara", lat: 13.05, lng: -14.3 },
  { name: "Kandiaye", slug: "kandiaye", departmentSlug: "velingara", lat: 13.1, lng: -14.2 },
  { name: "Linkering", slug: "linkering", departmentSlug: "velingara", lat: 13.2, lng: -14.3 },
  // Note : homonyme de "Médina Gounass" (commune du département de Guédiawaye,
  // région de Dakar) ; ce Médina Gounass-ci, en Haute Casamance, est l'un des plus
  // grands foyers religieux tidianes du pays. Slug suffixé pour éviter le doublon.
  { name: "Médina Gounass", slug: "medina-gounass-velingara", departmentSlug: "velingara", lat: 12.95, lng: -14.15, description: "Important foyer religieux tidiane de Haute Casamance, fondé par El Hadj Mamadou Saïdou Ba." },
  { name: "Némataba", slug: "nemataba", departmentSlug: "velingara", lat: 13.3, lng: -14.3 },
  { name: "Ouassadou", slug: "ouassadou", departmentSlug: "velingara", lat: 12.95, lng: -14.0 },
  { name: "Pakour", slug: "pakour", departmentSlug: "velingara", lat: 13.4, lng: -14.2 },
  { name: "Paroumba", slug: "paroumba", departmentSlug: "velingara", lat: 13.25, lng: -14.0 },
  { name: "Saré Coly Sallé", slug: "sare-coly-salle", departmentSlug: "velingara", lat: 13.05, lng: -14.1 },
  { name: "Sinthiang Koundara", slug: "sinthiang-koundara", departmentSlug: "velingara", lat: 13.35, lng: -13.9 },
  // Bounkiling (département) — référentiel officiel, 14 communes
  { name: "Boghal", slug: "boghal", departmentSlug: "bounkiling", lat: 12.95, lng: -15.55 },
  { name: "Bona", slug: "bona", departmentSlug: "bounkiling", lat: 12.75, lng: -15.85 },
  { name: "Bounkiling", slug: "bounkiling", departmentSlug: "bounkiling", lat: 12.8333, lng: -15.7, population: 10000 },
  { name: "Madina Wandifa", slug: "madina-wandifa", departmentSlug: "bounkiling", lat: 12.9, lng: -15.75 },
  { name: "Ndiamacouta", slug: "ndiamacouta", departmentSlug: "bounkiling", lat: 12.7, lng: -15.6 },
  { name: "Diacounda", slug: "diacounda", departmentSlug: "bounkiling", lat: 12.85, lng: -15.6 },
  { name: "Diambaty", slug: "diambaty", departmentSlug: "bounkiling", lat: 12.95, lng: -15.65 },
  { name: "Diaroumé", slug: "diaroume", departmentSlug: "bounkiling", lat: 12.8, lng: -15.5 },
  { name: "Djinany", slug: "djinany", departmentSlug: "bounkiling", lat: 12.65, lng: -15.75 },
  { name: "Faoune", slug: "faoune", departmentSlug: "bounkiling", lat: 12.9, lng: -15.85 },
  { name: "Inor", slug: "inor", departmentSlug: "bounkiling", lat: 12.75, lng: -15.55 },
  { name: "Kandion Mangana", slug: "kandion-mangana", departmentSlug: "bounkiling", lat: 12.7, lng: -15.9 },
  { name: "Ndiamalathiel", slug: "ndiamalathiel", departmentSlug: "bounkiling", lat: 12.85, lng: -15.8 },
  { name: "Tankon", slug: "tankon", departmentSlug: "bounkiling", lat: 12.95, lng: -15.6 },
  // Goudomp (département) — référentiel officiel, 15 communes
  { name: "Baghère", slug: "baghere", departmentSlug: "goudomp", lat: 12.45, lng: -15.6 },
  { name: "Diattacounda", slug: "diattacounda", departmentSlug: "goudomp", lat: 12.4, lng: -15.35 },
  { name: "Goudomp", slug: "goudomp", departmentSlug: "goudomp", lat: 12.5167, lng: -15.45, population: 9000 },
  { name: "Samine", slug: "samine", departmentSlug: "goudomp", lat: 12.55, lng: -15.55 },
  { name: "Tanaff", slug: "tanaff", departmentSlug: "goudomp", lat: 12.6, lng: -15.65 },
  { name: "Dioubadou", slug: "dioubadou", departmentSlug: "goudomp", lat: 12.5, lng: -15.65 },
  { name: "Djibanar", slug: "djibanar", departmentSlug: "goudomp", lat: 12.45, lng: -15.5 },
  { name: "Kaour", slug: "kaour", departmentSlug: "goudomp", lat: 12.35, lng: -15.55 },
  { name: "Karantaba", slug: "karantaba", departmentSlug: "goudomp", lat: 12.4, lng: -15.6 },
  { name: "Kolibantang", slug: "kolibantang", departmentSlug: "goudomp", lat: 12.6, lng: -15.5 },
  { name: "Mangaroungou Santo", slug: "mangaroungou-santo", departmentSlug: "goudomp", lat: 12.3, lng: -15.5 },
  { name: "Niagha", slug: "niagha", departmentSlug: "goudomp", lat: 12.55, lng: -15.35 },
  { name: "Simbadi Balante", slug: "simbadi-balante", departmentSlug: "goudomp", lat: 12.65, lng: -15.55 },
  { name: "Simbandi Brassou", slug: "simbandi-brassou", departmentSlug: "goudomp", lat: 12.35, lng: -15.65 },
  { name: "Yarang Balante", slug: "yarang-balante", departmentSlug: "goudomp", lat: 12.45, lng: -15.4 },
  // Sédhiou (département) — référentiel officiel, 14 communes
  { name: "Bambali", slug: "bambali", departmentSlug: "sedhiou-dept", lat: 12.75, lng: -15.5 },
  { name: "Bénet-Bijini", slug: "benet-bijini", departmentSlug: "sedhiou-dept", lat: 12.6, lng: -15.45 },
  { name: "Dianah Malary", slug: "dianah-malary", departmentSlug: "sedhiou-dept", lat: 12.65, lng: -15.4 },
  { name: "Marsassoum", slug: "marsassoum", departmentSlug: "sedhiou-dept", lat: 12.8, lng: -15.95 },
  { name: "Sédhiou", slug: "sedhiou", departmentSlug: "sedhiou-dept", lat: 12.7081, lng: -15.5569, population: 30000 },
  { name: "Diannah Ba", slug: "diannah-ba", departmentSlug: "sedhiou-dept", lat: 12.65, lng: -15.5 },
  { name: "Diendé", slug: "diende", departmentSlug: "sedhiou-dept", lat: 12.7, lng: -15.45 },
  { name: "Djibabouya", slug: "djibabouya", departmentSlug: "sedhiou-dept", lat: 12.75, lng: -15.6 },
  { name: "Djirédji", slug: "djiredji", departmentSlug: "sedhiou-dept", lat: 12.8, lng: -15.45 },
  { name: "Koussy", slug: "koussy", departmentSlug: "sedhiou-dept", lat: 12.6, lng: -15.6 },
  { name: "Oudoucar", slug: "oudoucar", departmentSlug: "sedhiou-dept", lat: 12.7, lng: -15.65 },
  { name: "Sakar", slug: "sakar", departmentSlug: "sedhiou-dept", lat: 12.85, lng: -15.55 },
  { name: "Sama Kanta Peulh", slug: "sama-kanta-peulh", departmentSlug: "sedhiou-dept", lat: 12.55, lng: -15.45 },
  { name: "Sansamba", slug: "sansamba", departmentSlug: "sedhiou-dept", lat: 12.9, lng: -15.5 },
  // Bignona (département) — référentiel officiel, 18 communes.
  // Note : "Mlomp" apparaissait dans la liste source à la fois sous Bignona et sous
  // Oussouye ; c'est géographiquement une commune d'Oussouye (Basse Casamance), donc
  // elle n'est conservée qu'une fois, sous Oussouye, pour éviter le doublon.
  { name: "Balingore", slug: "balingore", departmentSlug: "bignona", lat: 12.95, lng: -16.25 },
  { name: "Bignona", slug: "bignona", departmentSlug: "bignona", lat: 12.8167, lng: -16.2333, population: 40000 },
  { name: "Diouloulou", slug: "diouloulou", departmentSlug: "bignona", lat: 13.05, lng: -16.2667 },
  { name: "Thionck-Essyl", slug: "thionck-essyl", departmentSlug: "bignona", lat: 12.9333, lng: -16.3667 },
  { name: "Coubalan", slug: "coubalan", departmentSlug: "bignona", lat: 12.7333, lng: -16.2833 },
  { name: "Diégoune", slug: "diegoune", departmentSlug: "bignona", lat: 12.8667, lng: -16.2167 },
  { name: "Djibidione", slug: "djibidione", departmentSlug: "bignona", lat: 12.8, lng: -16.1333 },
  { name: "Djinaki", slug: "djinaki", departmentSlug: "bignona", lat: 12.7667, lng: -16.2667 },
  { name: "Kafountine", slug: "kafountine", departmentSlug: "bignona", lat: 12.9333, lng: -16.5667, description: "Village de pêcheurs et station balnéaire réputée de la Casamance." },
  { name: "Karthiack", slug: "karthiack", departmentSlug: "bignona", lat: 12.8667, lng: -16.0667 },
  { name: "Kataba I", slug: "kataba-i", departmentSlug: "bignona", lat: 12.8833, lng: -16.1667 },
  { name: "Mangagoulack", slug: "mangagoulack", departmentSlug: "bignona", lat: 12.6167, lng: -16.45 },
  { name: "Niamone", slug: "niamone", departmentSlug: "bignona", lat: 12.75, lng: -16.1833 },
  { name: "Oulampane", slug: "oulampane", departmentSlug: "bignona", lat: 12.9, lng: -16.3 },
  { name: "Ouonck", slug: "ouonck", departmentSlug: "bignona", lat: 12.8333, lng: -16.4667 },
  { name: "Sindian", slug: "sindian", departmentSlug: "bignona", lat: 13.0167, lng: -16.3333 },
  { name: "Suelle", slug: "suelle", departmentSlug: "bignona", lat: 12.9667, lng: -16.2 },
  { name: "Tenghory", slug: "tenghory", departmentSlug: "bignona", lat: 12.9833, lng: -16.4333 },
  // Oussouye (département) — référentiel officiel, 5 communes
  { name: "Oussouye", slug: "oussouye", departmentSlug: "oussouye", lat: 12.4833, lng: -16.55, population: 7000 },
  { name: "Djembering", slug: "djembering", departmentSlug: "oussouye", lat: 12.3833, lng: -16.6833 },
  { name: "Mlomp", slug: "mlomp", departmentSlug: "oussouye", lat: 12.45, lng: -16.6333 },
  { name: "Oukout", slug: "oukout", departmentSlug: "oussouye", lat: 12.3667, lng: -16.7167, description: "Commune côtière proche de Cap Skirring, en Basse Casamance." },
  { name: "Santhiaba Manjacque", slug: "santhiaba-manjacque", departmentSlug: "oussouye", lat: 12.5167, lng: -16.5167 },
  // Ziguinchor (département) — référentiel officiel, 6 communes
  { name: "Adéane", slug: "adeane", departmentSlug: "ziguinchor-dept", lat: 12.6167, lng: -16.1667 },
  { name: "Boutoupa Camar", slug: "boutoupa-camar", departmentSlug: "ziguinchor-dept", lat: 12.65, lng: -16.1167 },
  { name: "Ziguinchor", slug: "ziguinchor", departmentSlug: "ziguinchor-dept", lat: 12.5681, lng: -16.2719, population: 230000, description: "Capitale de la Casamance, principal centre urbain du sud du Sénégal." },
  { name: "Enampore", slug: "enampore", departmentSlug: "ziguinchor-dept", lat: 12.5167, lng: -16.3833 },
  { name: "Niaguis", slug: "niaguis", departmentSlug: "ziguinchor-dept", lat: 12.4833, lng: -16.2833 },
  { name: "Nyassia", slug: "nyassia", departmentSlug: "ziguinchor-dept", lat: 12.45, lng: -16.35 },
];
